import type { CodeLanguage, CodeThemeDetail } from './code-highlighter.type.js';

export const THEME_MAP = {
  'vs-code-dark-modern': {
    utility: [79, 193, 255],
    keyword: [197, 134, 192],
    method: [220, 220, 170],
    string: [206, 145, 120],
    type: [78, 201, 176],
    number: [181, 206, 168],
    operator: [244, 135, 113],
    variable: [156, 220, 254],
    comment: [106, 153, 85],
  } satisfies CodeThemeDetail,
};

export const KEYWORD_MAP: Record<
  CodeLanguage,
  { keywords: readonly string[]; types: readonly string[] }
> = {
  ts: {
    keywords: [
      'as',
      'async',
      'await',
      'const',
      'declare',
      'else',
      'enum',
      'export',
      'extends',
      'false',
      'from',
      'function',
      'if',
      'implements',
      'import',
      'interface',
      'keyof',
      'let',
      'namespace',
      'new',
      'null',
      'of',
      'private',
      'protected',
      'public',
      'readonly',
      'return',
      'satisfies',
      'static',
      'throw',
      'true',
      'type',
      'typeof',
      'undefined',
      'unknown',
      'void',
      'while',
    ],
    types: [
      'Array',
      'bigint',
      'boolean',
      'Date',
      'Function',
      'Map',
      'never',
      'number',
      'object',
      'Omit',
      'Partial',
      'Pick',
      'Promise',
      'PromiseLike',
      'Record',
      'Readonly',
      'Set',
      'string',
      'symbol',
      'unknown',
      'void',
    ],
  },
  js: {
    keywords: [
      'async',
      'await',
      'const',
      'else',
      'export',
      'extends',
      'false',
      'from',
      'function',
      'if',
      'import',
      'let',
      'new',
      'null',
      'of',
      'return',
      'throw',
      'true',
      'typeof',
      'undefined',
      'var',
      'while',
      'class',
      'this',
      'try',
      'catch',
      'finally',
    ],
    types: [],
  },
};
